version: '3'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root      
    ports:
      - "5432:5432"
    volumes:
      - ./internal/infrastructure/persistence/migration/init-database.sql:/docker-entrypoint-initdb.d/init-database.sql   